eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8090
spring:
  application:
    name: product
  config:
    import: optional:configserver:http:/localhost:8888

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/products
    username: adam
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  docker:
    compose:
      file: ./product/compose.yaml