version: '3.1'
services:
  product:
    image: "postgres:11-alpine"
    container_name: product
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=adam
      - POSTGRES_PASSWORD=password
    restart: always