eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8060
spring:
  application:
    name: cart
  config:
    import: optional:configserver:http:/localhost:8888

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/carts
    username: adam
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  docker:
    compose:
      file: ./cart/compose.yaml


application:
  config:
    product-url: http://localhost:8090/api/v1