eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8061
spring:
  application:
    name: auth-service

application:
  config:
    product-url: http://localhost:8080/api/v1/user

application-title: Auth Service
application-description: Some description
application-license: API Licence
application-version: 1.0