eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8060
spring:
  application:
    name: cart
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/carts
    username: adam
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis
    host: localhost
    port: 6379

application:
  config:
    product-url: http://localhost:8080/api/v1

management:
  tracing:
    sampling:
      probability: 1.0