eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8050
spring:
  application:
    name: category

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/categories
    username: adam
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis
    host: localhost
    port: 6379

  docker:
    compose:
      file: ./category/compose.yaml

application:
  config:
    product-url: http://localhost:8222/api/v1

management:
  tracing:
    sampling:
      probability: 1.0