eureka:
  client:
    register-with-eureka: false

server:
  port: 8222
spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/product/**,/api/v1/productVariant/**
        - id: cart
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/cart/**,/api/v1/cartItem/**
        - id: user
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/user/**
        - id: category
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/category/**,/api/v1/subcategory/**
management:
  tracing:
    sampling:
      probability: 1.0