eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8090
spring:
  application:
    name: product

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/ecommerce
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/products
    username: adam
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis
    host: localhost
    port: 6379

  docker:
    compose:
      file: ./product/compose.yaml

management:
  tracing:
    sampling:
      probability: 1.0

jwt:
  auth:
    converter:
      resource-id: ecommerce
      principle-attribute: preferred_username