version: '3.1'
services:
  user:
    image: "postgres:11-alpine"
    container_name: user
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=adam
      - POSTGRES_PASSWORD=password
    restart: always